/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrigo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rene
 */
public class Comidas_pre extends javax.swing.JFrame {

    /**
     * Creates new form Comidas_pre
     */
    public Comidas_pre() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../img//recursos/Icono.png")).getImage());
        
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(53);
        Tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
        Tabla.getColumnModel().getColumn(2).setPreferredWidth(120);
        Tabla.getColumnModel().getColumn(3).setPreferredWidth(300);
        
        Conectar con = new Conectar();
        Connection co = con.conexion();
        String sql = "SELECT id,calorias,comida,titulo FROM comidas_predeterminadas";
        String []datos_1000 = new String [4];
        Statement st;
        try {
            st = co.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos_1000[0] =rs.getString("id");
                datos_1000[1]=rs.getString("calorias");
                datos_1000[2]=rs.getString("comida");
                datos_1000[3]=rs.getString("titulo");
                modelo.addRow(datos_1000);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al taratar de mostrar los alimentos predeterminados");
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alimentos predeterminados");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Calorias", "Tipo de alimento", "Titulo"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/agregar.png"))); // NOI18N
        jButton1.setText("Ingresar nuevo alimento");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/eliminar.png"))); // NOI18N
        jButton2.setText("Borrar alimento");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botones/editar.png"))); // NOI18N
        jButton3.setText("Editar alimento");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ingresar_comida_pre ing = new Ingresar_comida_pre();
        ing.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = Tabla.getSelectedRow();
        if (fila != -1){
            int x = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar este alimento?", "Eliminar alimento", JOptionPane.YES_NO_OPTION);
            if (x == 0){
                try{
                    int row = Tabla.getSelectedRow();
                    String reg = (String) Tabla.getValueAt(row, 0);
                    int registro = Integer.parseInt(reg);
                    Conectar con = new Conectar();
                    Connection co = con.conexion();
                    Statement stm = co.createStatement();
                    String eliminar = "DELETE FROM comidas_predeterminadas WHERE id=" + registro;
                    stm.executeUpdate(eliminar);
                    JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
                    
                    DefaultTableModel modelo=(DefaultTableModel) Tabla.getModel();
                    int filas = Tabla.getRowCount();
                    for (int i = 0;filas>i; i++)
                    {
                        modelo.removeRow(0);
                    }
                    
                    String sql = "SELECT id,calorias,comida,titulo FROM comidas_predeterminadas";
                    String []datos_1000 = new String [4];
                    Statement st;
                    st = co.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while(rs.next()){
                        datos_1000[0] =rs.getString("id");
                        datos_1000[1]=rs.getString("calorias");
                        datos_1000[2]=rs.getString("comida");
                        datos_1000[3]=rs.getString("titulo");
                        modelo.addRow(datos_1000);
                    }
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el registro, intentelo nuevamente");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Para eliminar un alimento, primero debe seleccionar su fila en la tabla superior");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = Tabla.getSelectedRow();
        if (fila != -1){
            Editar_comida_pre ed = new Editar_comida_pre();
            ed.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Para editar un alimento, primero selecciona su respectiva fila en la tabla superior");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comidas_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comidas_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comidas_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comidas_pre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comidas_pre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
