/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrigo;

import javax.swing.ImageIcon;

/**
 *
 * @author Rene
 */
public class Ingresar_paciente_4 extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar_paciente_4
     */
    public Ingresar_paciente_4() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../img//recursos/Icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edema = new javax.swing.JRadioButton();
        piel_1 = new javax.swing.JRadioButton();
        piel_7 = new javax.swing.JRadioButton();
        cuello_1 = new javax.swing.JRadioButton();
        dientes_3 = new javax.swing.JRadioButton();
        dientes_1 = new javax.swing.JRadioButton();
        rostro_1 = new javax.swing.JRadioButton();
        dientes_2 = new javax.swing.JRadioButton();
        nervioso_1 = new javax.swing.JRadioButton();
        unas_2 = new javax.swing.JRadioButton();
        unas_1 = new javax.swing.JRadioButton();
        piel_2 = new javax.swing.JRadioButton();
        obesidad = new javax.swing.JRadioButton();
        nervioso_3 = new javax.swing.JRadioButton();
        nervioso_2 = new javax.swing.JRadioButton();
        cuello_2 = new javax.swing.JRadioButton();
        piel_4 = new javax.swing.JRadioButton();
        piel_6 = new javax.swing.JRadioButton();
        piel_5 = new javax.swing.JRadioButton();
        piel_3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boca_1 = new javax.swing.JRadioButton();
        rostro_2 = new javax.swing.JRadioButton();
        rostro_3 = new javax.swing.JRadioButton();
        boca_6 = new javax.swing.JRadioButton();
        boca_2 = new javax.swing.JRadioButton();
        boca_3 = new javax.swing.JRadioButton();
        boca_5 = new javax.swing.JRadioButton();
        boca_4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ojos_1 = new javax.swing.JRadioButton();
        ojos_2 = new javax.swing.JRadioButton();
        ojos_3 = new javax.swing.JRadioButton();
        ojos_4 = new javax.swing.JRadioButton();
        ojos_5 = new javax.swing.JRadioButton();
        gastro_1 = new javax.swing.JRadioButton();
        torax_4 = new javax.swing.JRadioButton();
        torax_3 = new javax.swing.JRadioButton();
        torax_2 = new javax.swing.JRadioButton();
        torax_1 = new javax.swing.JRadioButton();
        urinaria_1 = new javax.swing.JRadioButton();
        esqueleto_3 = new javax.swing.JRadioButton();
        urinaria_2 = new javax.swing.JRadioButton();
        esqueleto_2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        esqueleto_1 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresar juevo paciente");

        jPanel1.setBackground(new java.awt.Color(175, 228, 202));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Datos clínicos");

        jLabel1.setText("Seleccione los signos clinicos con los que cuenta el paciente");

        edema.setText("Edema");

        piel_1.setText("Falta de brillo en cabello");

        piel_7.setText("Falta de elastisidad");

        cuello_1.setText("Agrandamiento de tiroides");

        dientes_3.setText("Perdida de esmalte");

        dientes_1.setText("Fluorosis");

        rostro_1.setText("Cara de luna");

        dientes_2.setText("Falta de dientes, caries");

        nervioso_1.setText("Confusion mental");

        unas_2.setText("Despigmentacion, grietas");

        unas_1.setText("Uña coiliniquia");
        unas_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unas_1ActionPerformed(evt);
            }
        });

        piel_2.setText("Cabello signo de bandera");

        obesidad.setText("Obesidad");

        nervioso_3.setText("Dolor de cabeza, vomito o mareos");

        nervioso_2.setText("Disminucion de reflejos");

        cuello_2.setText("Agrandamiento de paratiroides");

        piel_4.setText("Problemas de cicatrizacion");

        piel_6.setText("Ceborrea  nasolabial");
        piel_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piel_6ActionPerformed(evt);
            }
        });

        piel_5.setText("Piel escamosa");

        piel_3.setText("Escaces de cabello");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Piel");

        jLabel3.setText("Uñas");

        jLabel4.setText("Ojos");

        jLabel5.setText("Rostro");

        jLabel6.setText("Boca");

        boca_1.setText("Atrofia papilar");

        rostro_2.setText("Parestesia facial");

        rostro_3.setText("Despigmentacion o hinchazon");

        boca_6.setText("Atrofia de la lengua");

        boca_2.setText("Glocitis");

        boca_3.setText("Lengua magenta o escarlata");

        boca_5.setText("Disminucion de gusto");

        boca_4.setText("Encias hinchadas");

        jLabel7.setText("Dientes");

        jLabel8.setText("Cuello");

        jLabel9.setText("Torax");

        jLabel10.setText("Sistema Nerviosos");

        ojos_1.setText("Manchas de bitot");

        ojos_2.setText("Keratomalasia");

        ojos_3.setText("Xerosis");

        ojos_4.setText("Ceguera nocturna");

        ojos_5.setText("Xantelasma");

        gastro_1.setText("Epatomegalia");
        gastro_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastro_1ActionPerformed(evt);
            }
        });

        torax_4.setText("Falla cardiaca");

        torax_3.setText("Disminucion de funcionamiento pulmonar");

        torax_2.setText("Falta de respiracion, fatiga");

        torax_1.setText("Disminusion de masa y fuerza muscular");

        urinaria_1.setText("Orina oscura y concentrada");

        esqueleto_3.setText("Piernas arqueadas");

        urinaria_2.setText("Orina clara y diluida");

        esqueleto_2.setText("Dolor en pantorrilla y muslos");

        jLabel11.setText("Vias urinarias");

        esqueleto_1.setText("Dolor de articulaciones");

        jLabel12.setText("Sistema esqueleto-muscular");

        jLabel13.setText("Sistema gastrointestinal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edema)
                                    .addComponent(jLabel3)
                                    .addComponent(unas_2))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nervioso_1)
                                    .addComponent(nervioso_2)
                                    .addComponent(jLabel10)
                                    .addComponent(nervioso_3)
                                    .addComponent(jLabel6)
                                    .addComponent(boca_1)
                                    .addComponent(boca_2)
                                    .addComponent(boca_3)
                                    .addComponent(boca_5)
                                    .addComponent(boca_6)
                                    .addComponent(boca_4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(cuello_1)
                                            .addComponent(cuello_2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addComponent(obesidad)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(esqueleto_2)
                                    .addComponent(esqueleto_3)
                                    .addComponent(esqueleto_1)
                                    .addComponent(jLabel12))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gastro_1)
                                    .addComponent(jLabel13))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rostro_1)
                                    .addComponent(rostro_2)
                                    .addComponent(rostro_3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(ojos_1)
                                    .addComponent(ojos_2)
                                    .addComponent(ojos_3)
                                    .addComponent(ojos_5)
                                    .addComponent(ojos_4))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dientes_1)
                                    .addComponent(dientes_2)
                                    .addComponent(dientes_3)
                                    .addComponent(jLabel7)
                                    .addComponent(piel_6)
                                    .addComponent(piel_2)
                                    .addComponent(jLabel2)
                                    .addComponent(piel_1)
                                    .addComponent(piel_3)
                                    .addComponent(piel_4)
                                    .addComponent(piel_5)
                                    .addComponent(piel_7))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(unas_1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(urinaria_1)
                                    .addComponent(urinaria_2)
                                    .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(torax_1)
                                    .addComponent(torax_2)
                                    .addComponent(torax_3)
                                    .addComponent(torax_4))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edema)
                    .addComponent(obesidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nervioso_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nervioso_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nervioso_3))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(unas_1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(unas_2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cuello_1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cuello_2)))
                                    .addGap(28, 28, 28))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dientes_1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dientes_2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dientes_3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(piel_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(piel_7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ojos_1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ojos_2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ojos_3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ojos_4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ojos_5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(torax_1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(torax_2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(torax_3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(torax_4)))
                                            .addGap(28, 28, 28)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(urinaria_1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(urinaria_2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boca_1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boca_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boca_3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boca_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boca_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boca_6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(esqueleto_1)
                                    .addComponent(gastro_1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(esqueleto_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(esqueleto_3)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rostro_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rostro_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rostro_3)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unas_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unas_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unas_1ActionPerformed

    private void piel_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piel_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piel_6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Ingresar_paciente_enviar.edema = (edema.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.obesidad = (obesidad.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.unas1 = (unas_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.unas2 = (unas_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.cuello1 = (cuello_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.cuello2 = (cuello_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.nervioso1 = (nervioso_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.nervioso2 = (nervioso_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.nervioso3 = (nervioso_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.rostro1 = (rostro_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.rostro2 = (rostro_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.rostro3 = (rostro_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.dientes1 = (dientes_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.dientes2 = (dientes_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.dientes3 = (dientes_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.urinaria1 = (urinaria_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.urinaria2 = (urinaria_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.torax1 = (torax_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.torax2 = (torax_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.torax3 = (torax_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.torax4 = (torax_4.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca1 = (boca_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca2 = (boca_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca3 = (boca_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca4 = (boca_4.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca5 = (boca_5.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.boca6 = (boca_6.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.ojos1 = (ojos_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.ojos2 = (ojos_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.ojos3 = (ojos_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.ojos4 = (ojos_4.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.ojos5 = (ojos_5.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel1 = (piel_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel2 = (piel_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel3 = (piel_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel4 = (piel_4.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel5 = (piel_5.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel6 = (piel_6.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.piel7 = (piel_7.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.esqueleto1 = (esqueleto_1.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.esqueleto2 = (esqueleto_2.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.esqueleto3 = (esqueleto_3.isSelected()) ? 1:0;
        Ingresar_paciente_enviar.gastro1 = (gastro_1.isSelected()) ? 1:0;
        Ingresar_paciente_5 siguiente = new Ingresar_paciente_5();
        siguiente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gastro_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastro_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastro_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_paciente_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_paciente_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_paciente_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_paciente_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_paciente_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boca_1;
    private javax.swing.JRadioButton boca_2;
    private javax.swing.JRadioButton boca_3;
    private javax.swing.JRadioButton boca_4;
    private javax.swing.JRadioButton boca_5;
    private javax.swing.JRadioButton boca_6;
    private javax.swing.JRadioButton cuello_1;
    private javax.swing.JRadioButton cuello_2;
    private javax.swing.JRadioButton dientes_1;
    private javax.swing.JRadioButton dientes_2;
    private javax.swing.JRadioButton dientes_3;
    private javax.swing.JRadioButton edema;
    private javax.swing.JRadioButton esqueleto_1;
    private javax.swing.JRadioButton esqueleto_2;
    private javax.swing.JRadioButton esqueleto_3;
    private javax.swing.JRadioButton gastro_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nervioso_1;
    private javax.swing.JRadioButton nervioso_2;
    private javax.swing.JRadioButton nervioso_3;
    private javax.swing.JRadioButton obesidad;
    private javax.swing.JRadioButton ojos_1;
    private javax.swing.JRadioButton ojos_2;
    private javax.swing.JRadioButton ojos_3;
    private javax.swing.JRadioButton ojos_4;
    private javax.swing.JRadioButton ojos_5;
    private javax.swing.JRadioButton piel_1;
    private javax.swing.JRadioButton piel_2;
    private javax.swing.JRadioButton piel_3;
    private javax.swing.JRadioButton piel_4;
    private javax.swing.JRadioButton piel_5;
    private javax.swing.JRadioButton piel_6;
    private javax.swing.JRadioButton piel_7;
    private javax.swing.JRadioButton rostro_1;
    private javax.swing.JRadioButton rostro_2;
    private javax.swing.JRadioButton rostro_3;
    private javax.swing.JRadioButton torax_1;
    private javax.swing.JRadioButton torax_2;
    private javax.swing.JRadioButton torax_3;
    private javax.swing.JRadioButton torax_4;
    private javax.swing.JRadioButton unas_1;
    private javax.swing.JRadioButton unas_2;
    private javax.swing.JRadioButton urinaria_1;
    private javax.swing.JRadioButton urinaria_2;
    // End of variables declaration//GEN-END:variables
}
