/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutrigo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author Rene
 */
public class Ver_dieta extends javax.swing.JFrame {

    /**
     * Creates new form Ver_dieta
     */
    public Ver_dieta() {
        initComponents();
        
        JTextArea[] cuadros = new JTextArea[70];
        cuadros[0] = t_desayuno_1;
        cuadros[1] = t_desayuno_2;
        cuadros[2] = t_desayuno_3;
        cuadros[3] = t_desayuno_4;
        cuadros[4] = t_desayuno_5;
        cuadros[5] = t_desayuno_6;
        cuadros[6] = t_desayuno_7;
        cuadros[7] = t_colacion1_1;
        cuadros[8] = t_colacion1_2;
        cuadros[9] = t_colacion1_3;
        cuadros[10] = t_colacion1_4;
        cuadros[11] = t_colacion1_5;
        cuadros[12] = t_colacion1_6;
        cuadros[13] = t_colacion1_7;
        cuadros[14] = t_comida_1;
        cuadros[15] = t_comida_2;
        cuadros[16] = t_comida_3;
        cuadros[17] = t_comida_4;
        cuadros[18] = t_comida_5;
        cuadros[19] = t_comida_6;
        cuadros[20] = t_comida_7;
        cuadros[21] = t_colacion2_1;
        cuadros[22] = t_colacion2_2;
        cuadros[23] = t_colacion2_3;
        cuadros[24] = t_colacion2_4;
        cuadros[25] = t_colacion2_5;
        cuadros[26] = t_colacion2_6;
        cuadros[27] = t_colacion2_7;
        cuadros[28] = t_cena_1;
        cuadros[29] = t_cena_2;
        cuadros[30] = t_cena_3;
        cuadros[31] = t_cena_4;
        cuadros[32] = t_cena_5;
        cuadros[33] = t_cena_6;
        cuadros[34] = t_cena_7;
        cuadros[35] = desayuno_1;
        cuadros[36] = desayuno_2;
        cuadros[37] = desayuno_3;
        cuadros[38] = desayuno_4;
        cuadros[39] = desayuno_5;
        cuadros[40] = desayuno_6;
        cuadros[41] = desayuno_7;
        cuadros[42] = colacion1_1;
        cuadros[43] = colacion1_2;
        cuadros[44] = colacion1_3;
        cuadros[45] = colacion1_4;
        cuadros[46] = colacion1_5;
        cuadros[47] = colacion1_6;
        cuadros[48] = colacion1_7;
        cuadros[49] = comida_1;
        cuadros[50] = comida_2;
        cuadros[51] = comida_3;
        cuadros[52] = comida_4;
        cuadros[53] = comida_5;
        cuadros[54] = comida_6;
        cuadros[55] = comida_7;
        cuadros[56] = colacion2_1;
        cuadros[57] = colacion2_2;
        cuadros[58] = colacion2_3;
        cuadros[59] = colacion2_4;
        cuadros[60] = colacion2_5;
        cuadros[61] = colacion2_6;
        cuadros[62] = colacion2_7;
        cuadros[63] = cena_1;
        cuadros[64] = cena_2;
        cuadros[65] = cena_3;
        cuadros[66] = cena_4;
        cuadros[67] = cena_5;
        cuadros[68] = cena_6;
        cuadros[69] = cena_7;
        
        
        int row = Panel_Dietas.Tabla.getSelectedRow();
        String reg = (String) Panel_Dietas.Tabla.getValueAt(row, 1);
        int registro = Integer.parseInt(reg);
        int fila = Panel_Dietas.Tabla.getSelectedRow();
        String cal = (String) Panel_Dietas.Tabla.getValueAt(fila, 0);
        int calorias = Integer.parseInt(cal);
        Conectar con = new Conectar();
        Connection co = con.conexion();
        String sql = "";
        if (calorias == 1000){
            sql = "SELECT * FROM dietas_1000 WHERE id=" + registro;
        }
        else if (calorias == 1200){
            sql = "SELECT * FROM dietas_1200 WHERE id=" + registro;
        }
        else if (calorias == 1400){
            sql = "SELECT * FROM dietas_1400 WHERE id=" + registro;
        }
        else if (calorias == 1600){
            sql = "SELECT * FROM dietas_1600 WHERE id=" + registro;
        }
        else{
            sql = "SELECT * FROM dietas_1800 WHERE id=" + registro;
        }
        Statement st;
        String[] texto = new String[70];
        int i = 4;
        try {
            st = co.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                while (i<74){
                    texto[i-4] = rs.getString(i);
                    i++;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ver_dieta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (i=0; i<70;i++){
            cuadros[i].setText(texto[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        cena_2 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        t_cena_2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        t_desayuno_2 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        desayuno_2 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        t_colacion1_2 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        t_comida_2 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        t_colacion2_2 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        colacion2_2 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        comida_2 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        colacion1_2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane31 = new javax.swing.JScrollPane();
        cena_3 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        t_cena_3 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane33 = new javax.swing.JScrollPane();
        t_desayuno_3 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        desayuno_3 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        t_colacion1_3 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        t_comida_3 = new javax.swing.JTextArea();
        jScrollPane37 = new javax.swing.JScrollPane();
        t_colacion2_3 = new javax.swing.JTextArea();
        jScrollPane38 = new javax.swing.JScrollPane();
        colacion2_3 = new javax.swing.JTextArea();
        jScrollPane39 = new javax.swing.JScrollPane();
        comida_3 = new javax.swing.JTextArea();
        jScrollPane40 = new javax.swing.JScrollPane();
        colacion1_3 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane41 = new javax.swing.JScrollPane();
        cena_4 = new javax.swing.JTextArea();
        jScrollPane42 = new javax.swing.JScrollPane();
        t_cena_4 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane43 = new javax.swing.JScrollPane();
        t_desayuno_4 = new javax.swing.JTextArea();
        jScrollPane44 = new javax.swing.JScrollPane();
        desayuno_4 = new javax.swing.JTextArea();
        jScrollPane45 = new javax.swing.JScrollPane();
        t_colacion1_4 = new javax.swing.JTextArea();
        jScrollPane46 = new javax.swing.JScrollPane();
        t_comida_4 = new javax.swing.JTextArea();
        jScrollPane47 = new javax.swing.JScrollPane();
        t_colacion2_4 = new javax.swing.JTextArea();
        jScrollPane48 = new javax.swing.JScrollPane();
        colacion2_4 = new javax.swing.JTextArea();
        jScrollPane49 = new javax.swing.JScrollPane();
        comida_4 = new javax.swing.JTextArea();
        jScrollPane50 = new javax.swing.JScrollPane();
        colacion1_4 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane51 = new javax.swing.JScrollPane();
        cena_5 = new javax.swing.JTextArea();
        jScrollPane52 = new javax.swing.JScrollPane();
        t_cena_5 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane53 = new javax.swing.JScrollPane();
        t_desayuno_5 = new javax.swing.JTextArea();
        jScrollPane54 = new javax.swing.JScrollPane();
        desayuno_5 = new javax.swing.JTextArea();
        jScrollPane55 = new javax.swing.JScrollPane();
        t_colacion1_5 = new javax.swing.JTextArea();
        jScrollPane56 = new javax.swing.JScrollPane();
        t_comida_5 = new javax.swing.JTextArea();
        jScrollPane57 = new javax.swing.JScrollPane();
        t_colacion2_5 = new javax.swing.JTextArea();
        jScrollPane58 = new javax.swing.JScrollPane();
        colacion2_5 = new javax.swing.JTextArea();
        jScrollPane59 = new javax.swing.JScrollPane();
        comida_5 = new javax.swing.JTextArea();
        jScrollPane60 = new javax.swing.JScrollPane();
        colacion1_5 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane61 = new javax.swing.JScrollPane();
        cena_6 = new javax.swing.JTextArea();
        jScrollPane62 = new javax.swing.JScrollPane();
        t_cena_6 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane63 = new javax.swing.JScrollPane();
        t_desayuno_6 = new javax.swing.JTextArea();
        jScrollPane64 = new javax.swing.JScrollPane();
        desayuno_6 = new javax.swing.JTextArea();
        jScrollPane65 = new javax.swing.JScrollPane();
        t_colacion1_6 = new javax.swing.JTextArea();
        jScrollPane66 = new javax.swing.JScrollPane();
        t_comida_6 = new javax.swing.JTextArea();
        jScrollPane67 = new javax.swing.JScrollPane();
        t_colacion2_6 = new javax.swing.JTextArea();
        jScrollPane68 = new javax.swing.JScrollPane();
        colacion2_6 = new javax.swing.JTextArea();
        jScrollPane69 = new javax.swing.JScrollPane();
        comida_6 = new javax.swing.JTextArea();
        jScrollPane70 = new javax.swing.JScrollPane();
        colacion1_6 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane71 = new javax.swing.JScrollPane();
        cena_7 = new javax.swing.JTextArea();
        jScrollPane72 = new javax.swing.JScrollPane();
        t_cena_7 = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane73 = new javax.swing.JScrollPane();
        t_desayuno_7 = new javax.swing.JTextArea();
        jScrollPane74 = new javax.swing.JScrollPane();
        desayuno_7 = new javax.swing.JTextArea();
        jScrollPane75 = new javax.swing.JScrollPane();
        t_colacion1_7 = new javax.swing.JTextArea();
        jScrollPane76 = new javax.swing.JScrollPane();
        t_comida_7 = new javax.swing.JTextArea();
        jScrollPane77 = new javax.swing.JScrollPane();
        t_colacion2_7 = new javax.swing.JTextArea();
        jScrollPane78 = new javax.swing.JScrollPane();
        colacion2_7 = new javax.swing.JTextArea();
        jScrollPane79 = new javax.swing.JScrollPane();
        comida_7 = new javax.swing.JTextArea();
        jScrollPane80 = new javax.swing.JScrollPane();
        colacion1_7 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        t_desayuno_1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        t_colacion1_1 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        t_comida_1 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        t_colacion2_1 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        t_cena_1 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        desayuno_1 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        colacion1_1 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        comida_1 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        colacion2_1 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        cena_1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(175, 228, 202));

        cena_2.setColumns(20);
        cena_2.setLineWrap(true);
        cena_2.setRows(3);
        jScrollPane21.setViewportView(cena_2);

        t_cena_2.setColumns(20);
        t_cena_2.setLineWrap(true);
        t_cena_2.setRows(3);
        jScrollPane22.setViewportView(t_cena_2);

        jLabel15.setText("Cena");

        jLabel16.setText("Colacion 2");

        jLabel17.setText("Comida");

        jLabel18.setText("Colacion 1");

        jLabel19.setText("Desayuno");

        jLabel20.setText("Titulo");

        jLabel21.setText("Ingredientes");

        t_desayuno_2.setColumns(20);
        t_desayuno_2.setLineWrap(true);
        t_desayuno_2.setRows(3);
        jScrollPane23.setViewportView(t_desayuno_2);

        desayuno_2.setColumns(20);
        desayuno_2.setLineWrap(true);
        desayuno_2.setRows(3);
        jScrollPane24.setViewportView(desayuno_2);

        t_colacion1_2.setColumns(20);
        t_colacion1_2.setLineWrap(true);
        t_colacion1_2.setRows(3);
        jScrollPane25.setViewportView(t_colacion1_2);

        t_comida_2.setColumns(20);
        t_comida_2.setLineWrap(true);
        t_comida_2.setRows(3);
        jScrollPane26.setViewportView(t_comida_2);

        t_colacion2_2.setColumns(20);
        t_colacion2_2.setLineWrap(true);
        t_colacion2_2.setRows(3);
        jScrollPane27.setViewportView(t_colacion2_2);

        colacion2_2.setColumns(20);
        colacion2_2.setLineWrap(true);
        colacion2_2.setRows(3);
        jScrollPane28.setViewportView(colacion2_2);

        comida_2.setColumns(20);
        comida_2.setLineWrap(true);
        comida_2.setRows(3);
        jScrollPane29.setViewportView(comida_2);

        colacion1_2.setColumns(20);
        colacion1_2.setLineWrap(true);
        colacion1_2.setRows(3);
        jScrollPane30.setViewportView(colacion1_2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(160, 160, 160))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane30, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel19))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel16)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel15)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Martes", jPanel3);

        jPanel4.setBackground(new java.awt.Color(175, 228, 202));

        cena_3.setColumns(20);
        cena_3.setLineWrap(true);
        cena_3.setRows(3);
        jScrollPane31.setViewportView(cena_3);

        t_cena_3.setColumns(20);
        t_cena_3.setLineWrap(true);
        t_cena_3.setRows(3);
        jScrollPane32.setViewportView(t_cena_3);

        jLabel22.setText("Cena");

        jLabel23.setText("Colacion 2");

        jLabel24.setText("Comida");

        jLabel25.setText("Colacion 1");

        jLabel26.setText("Desayuno");

        jLabel27.setText("Titulo");

        jLabel28.setText("Ingredientes");

        t_desayuno_3.setColumns(20);
        t_desayuno_3.setLineWrap(true);
        t_desayuno_3.setRows(3);
        jScrollPane33.setViewportView(t_desayuno_3);

        desayuno_3.setColumns(20);
        desayuno_3.setLineWrap(true);
        desayuno_3.setRows(3);
        jScrollPane34.setViewportView(desayuno_3);

        t_colacion1_3.setColumns(20);
        t_colacion1_3.setLineWrap(true);
        t_colacion1_3.setRows(3);
        jScrollPane35.setViewportView(t_colacion1_3);

        t_comida_3.setColumns(20);
        t_comida_3.setLineWrap(true);
        t_comida_3.setRows(3);
        jScrollPane36.setViewportView(t_comida_3);

        t_colacion2_3.setColumns(20);
        t_colacion2_3.setLineWrap(true);
        t_colacion2_3.setRows(3);
        jScrollPane37.setViewportView(t_colacion2_3);

        colacion2_3.setColumns(20);
        colacion2_3.setLineWrap(true);
        colacion2_3.setRows(3);
        jScrollPane38.setViewportView(colacion2_3);

        comida_3.setColumns(20);
        comida_3.setLineWrap(true);
        comida_3.setRows(3);
        jScrollPane39.setViewportView(comida_3);

        colacion1_3.setColumns(20);
        colacion1_3.setLineWrap(true);
        colacion1_3.setRows(3);
        jScrollPane40.setViewportView(colacion1_3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(160, 160, 160))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane40, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane34))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane39, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane38, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane31, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel26))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel23)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel22)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Miercoles", jPanel4);

        jPanel5.setBackground(new java.awt.Color(175, 228, 202));

        cena_4.setColumns(20);
        cena_4.setRows(3);
        jScrollPane41.setViewportView(cena_4);

        t_cena_4.setColumns(20);
        t_cena_4.setRows(3);
        jScrollPane42.setViewportView(t_cena_4);

        jLabel29.setText("Cena");

        jLabel30.setText("Colacion 2");

        jLabel31.setText("Comida");

        jLabel32.setText("Colacion 1");

        jLabel33.setText("Desayuno");

        jLabel34.setText("Titulo");

        jLabel35.setText("Ingredientes");

        t_desayuno_4.setColumns(20);
        t_desayuno_4.setRows(3);
        jScrollPane43.setViewportView(t_desayuno_4);

        desayuno_4.setColumns(20);
        desayuno_4.setRows(3);
        jScrollPane44.setViewportView(desayuno_4);

        t_colacion1_4.setColumns(20);
        t_colacion1_4.setRows(3);
        jScrollPane45.setViewportView(t_colacion1_4);

        t_comida_4.setColumns(20);
        t_comida_4.setRows(3);
        jScrollPane46.setViewportView(t_comida_4);

        t_colacion2_4.setColumns(20);
        t_colacion2_4.setRows(3);
        jScrollPane47.setViewportView(t_colacion2_4);

        colacion2_4.setColumns(20);
        colacion2_4.setRows(3);
        jScrollPane48.setViewportView(colacion2_4);

        comida_4.setColumns(20);
        comida_4.setRows(3);
        jScrollPane49.setViewportView(comida_4);

        colacion1_4.setColumns(20);
        colacion1_4.setRows(3);
        jScrollPane50.setViewportView(colacion1_4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(160, 160, 160))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane50, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane44))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane49, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane48, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane41, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel33))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel32))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel31)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel30)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel29)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Jueves", jPanel5);

        jPanel6.setBackground(new java.awt.Color(175, 228, 202));

        cena_5.setColumns(20);
        cena_5.setLineWrap(true);
        cena_5.setRows(3);
        jScrollPane51.setViewportView(cena_5);

        t_cena_5.setColumns(20);
        t_cena_5.setLineWrap(true);
        t_cena_5.setRows(3);
        jScrollPane52.setViewportView(t_cena_5);

        jLabel36.setText("Cena");

        jLabel37.setText("Colacion 2");

        jLabel38.setText("Comida");

        jLabel39.setText("Colacion 1");

        jLabel40.setText("Desayuno");

        jLabel41.setText("Titulo");

        jLabel42.setText("Ingredientes");

        t_desayuno_5.setColumns(20);
        t_desayuno_5.setLineWrap(true);
        t_desayuno_5.setRows(3);
        jScrollPane53.setViewportView(t_desayuno_5);

        desayuno_5.setColumns(20);
        desayuno_5.setLineWrap(true);
        desayuno_5.setRows(3);
        jScrollPane54.setViewportView(desayuno_5);

        t_colacion1_5.setColumns(20);
        t_colacion1_5.setLineWrap(true);
        t_colacion1_5.setRows(3);
        jScrollPane55.setViewportView(t_colacion1_5);

        t_comida_5.setColumns(20);
        t_comida_5.setLineWrap(true);
        t_comida_5.setRows(3);
        jScrollPane56.setViewportView(t_comida_5);

        t_colacion2_5.setColumns(20);
        t_colacion2_5.setLineWrap(true);
        t_colacion2_5.setRows(3);
        jScrollPane57.setViewportView(t_colacion2_5);

        colacion2_5.setColumns(20);
        colacion2_5.setLineWrap(true);
        colacion2_5.setRows(3);
        jScrollPane58.setViewportView(colacion2_5);

        comida_5.setColumns(20);
        comida_5.setLineWrap(true);
        comida_5.setRows(3);
        jScrollPane59.setViewportView(comida_5);

        colacion1_5.setColumns(20);
        colacion1_5.setLineWrap(true);
        colacion1_5.setRows(3);
        jScrollPane60.setViewportView(colacion1_5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGap(160, 160, 160))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel40)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane60, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane54))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane59, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane58, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane51, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel40))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel39))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel38)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel37)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel36)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane58, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Viernes", jPanel6);

        jPanel7.setBackground(new java.awt.Color(175, 228, 202));

        cena_6.setColumns(20);
        cena_6.setLineWrap(true);
        cena_6.setRows(3);
        jScrollPane61.setViewportView(cena_6);

        t_cena_6.setColumns(20);
        t_cena_6.setLineWrap(true);
        t_cena_6.setRows(3);
        jScrollPane62.setViewportView(t_cena_6);

        jLabel43.setText("Cena");

        jLabel44.setText("Colacion 2");

        jLabel45.setText("Comida");

        jLabel46.setText("Colacion 1");

        jLabel47.setText("Desayuno");

        jLabel48.setText("Titulo");

        jLabel49.setText("Ingredientes");

        t_desayuno_6.setColumns(20);
        t_desayuno_6.setLineWrap(true);
        t_desayuno_6.setRows(3);
        jScrollPane63.setViewportView(t_desayuno_6);

        desayuno_6.setColumns(20);
        desayuno_6.setLineWrap(true);
        desayuno_6.setRows(3);
        jScrollPane64.setViewportView(desayuno_6);

        t_colacion1_6.setColumns(20);
        t_colacion1_6.setLineWrap(true);
        t_colacion1_6.setRows(3);
        jScrollPane65.setViewportView(t_colacion1_6);

        t_comida_6.setColumns(20);
        t_comida_6.setLineWrap(true);
        t_comida_6.setRows(3);
        jScrollPane66.setViewportView(t_comida_6);

        t_colacion2_6.setColumns(20);
        t_colacion2_6.setLineWrap(true);
        t_colacion2_6.setRows(3);
        jScrollPane67.setViewportView(t_colacion2_6);

        colacion2_6.setColumns(20);
        colacion2_6.setLineWrap(true);
        colacion2_6.setRows(3);
        jScrollPane68.setViewportView(colacion2_6);

        comida_6.setColumns(20);
        comida_6.setLineWrap(true);
        comida_6.setRows(3);
        jScrollPane69.setViewportView(comida_6);

        colacion1_6.setColumns(20);
        colacion1_6.setLineWrap(true);
        colacion1_6.setRows(3);
        jScrollPane70.setViewportView(colacion1_6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addGap(160, 160, 160))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(jLabel47)
                    .addComponent(jLabel44)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane70, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane64))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane69, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane68, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane61, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel47))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane64, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane63, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel46))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane70, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane65, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel45)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel44)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel43)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane66, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane69, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane67, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane68, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane62, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane61, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Sabado", jPanel7);

        jPanel8.setBackground(new java.awt.Color(175, 228, 202));

        cena_7.setColumns(20);
        cena_7.setLineWrap(true);
        cena_7.setRows(3);
        jScrollPane71.setViewportView(cena_7);

        t_cena_7.setColumns(20);
        t_cena_7.setLineWrap(true);
        t_cena_7.setRows(3);
        jScrollPane72.setViewportView(t_cena_7);

        jLabel50.setText("Cena");

        jLabel51.setText("Colacion 2");

        jLabel52.setText("Comida");

        jLabel53.setText("Colacion 1");

        jLabel54.setText("Desayuno");

        jLabel55.setText("Titulo");

        jLabel56.setText("Ingredientes");

        t_desayuno_7.setColumns(20);
        t_desayuno_7.setLineWrap(true);
        t_desayuno_7.setRows(3);
        jScrollPane73.setViewportView(t_desayuno_7);

        desayuno_7.setColumns(20);
        desayuno_7.setLineWrap(true);
        desayuno_7.setRows(3);
        jScrollPane74.setViewportView(desayuno_7);

        t_colacion1_7.setColumns(20);
        t_colacion1_7.setLineWrap(true);
        t_colacion1_7.setRows(3);
        jScrollPane75.setViewportView(t_colacion1_7);

        t_comida_7.setColumns(20);
        t_comida_7.setLineWrap(true);
        t_comida_7.setRows(3);
        jScrollPane76.setViewportView(t_comida_7);

        t_colacion2_7.setColumns(20);
        t_colacion2_7.setLineWrap(true);
        t_colacion2_7.setRows(3);
        jScrollPane77.setViewportView(t_colacion2_7);

        colacion2_7.setColumns(20);
        colacion2_7.setLineWrap(true);
        colacion2_7.setRows(3);
        jScrollPane78.setViewportView(colacion2_7);

        comida_7.setColumns(20);
        comida_7.setLineWrap(true);
        comida_7.setRows(3);
        jScrollPane79.setViewportView(comida_7);

        colacion1_7.setColumns(20);
        colacion1_7.setLineWrap(true);
        colacion1_7.setRows(3);
        jScrollPane80.setViewportView(colacion1_7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel56)
                .addGap(160, 160, 160))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(jLabel54)
                    .addComponent(jLabel51)
                    .addComponent(jLabel53)
                    .addComponent(jLabel52))
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane80, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane74))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane79, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane78, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane71, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel56))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel54))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane74, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane73, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel53))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane80, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane75, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel51)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel50)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane76, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane79, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane77, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane78, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane72, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane71, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Domingo", jPanel8);

        jPanel2.setBackground(new java.awt.Color(175, 228, 202));

        jLabel8.setText("Desayuno");

        jLabel9.setText("Titulo");

        jLabel10.setText("Ingredientes");

        jLabel11.setText("Colacion 1");

        jLabel12.setText("Comida");

        jLabel13.setText("Colacion 2");

        jLabel14.setText("Cena");

        t_desayuno_1.setColumns(20);
        t_desayuno_1.setLineWrap(true);
        t_desayuno_1.setRows(3);
        jScrollPane11.setViewportView(t_desayuno_1);

        t_colacion1_1.setColumns(20);
        t_colacion1_1.setLineWrap(true);
        t_colacion1_1.setRows(3);
        jScrollPane12.setViewportView(t_colacion1_1);

        t_comida_1.setColumns(20);
        t_comida_1.setLineWrap(true);
        t_comida_1.setRows(3);
        jScrollPane13.setViewportView(t_comida_1);

        t_colacion2_1.setColumns(20);
        t_colacion2_1.setLineWrap(true);
        t_colacion2_1.setRows(3);
        jScrollPane14.setViewportView(t_colacion2_1);

        t_cena_1.setColumns(20);
        t_cena_1.setLineWrap(true);
        t_cena_1.setRows(3);
        jScrollPane15.setViewportView(t_cena_1);

        desayuno_1.setColumns(20);
        desayuno_1.setLineWrap(true);
        desayuno_1.setRows(3);
        jScrollPane16.setViewportView(desayuno_1);

        colacion1_1.setColumns(20);
        colacion1_1.setLineWrap(true);
        colacion1_1.setRows(3);
        jScrollPane17.setViewportView(colacion1_1);

        comida_1.setColumns(20);
        comida_1.setLineWrap(true);
        comida_1.setRows(3);
        jScrollPane18.setViewportView(comida_1);

        colacion2_1.setColumns(20);
        colacion2_1.setLineWrap(true);
        colacion2_1.setRows(3);
        jScrollPane19.setViewportView(colacion2_1);

        cena_1.setColumns(20);
        cena_1.setLineWrap(true);
        cena_1.setRows(3);
        jScrollPane20.setViewportView(cena_1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(160, 160, 160))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Lunes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_dieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cena_1;
    private javax.swing.JTextArea cena_2;
    private javax.swing.JTextArea cena_3;
    private javax.swing.JTextArea cena_4;
    private javax.swing.JTextArea cena_5;
    private javax.swing.JTextArea cena_6;
    private javax.swing.JTextArea cena_7;
    private javax.swing.JTextArea colacion1_1;
    private javax.swing.JTextArea colacion1_2;
    private javax.swing.JTextArea colacion1_3;
    private javax.swing.JTextArea colacion1_4;
    private javax.swing.JTextArea colacion1_5;
    private javax.swing.JTextArea colacion1_6;
    private javax.swing.JTextArea colacion1_7;
    private javax.swing.JTextArea colacion2_1;
    private javax.swing.JTextArea colacion2_2;
    private javax.swing.JTextArea colacion2_3;
    private javax.swing.JTextArea colacion2_4;
    private javax.swing.JTextArea colacion2_5;
    private javax.swing.JTextArea colacion2_6;
    private javax.swing.JTextArea colacion2_7;
    private javax.swing.JTextArea comida_1;
    private javax.swing.JTextArea comida_2;
    private javax.swing.JTextArea comida_3;
    private javax.swing.JTextArea comida_4;
    private javax.swing.JTextArea comida_5;
    private javax.swing.JTextArea comida_6;
    private javax.swing.JTextArea comida_7;
    private javax.swing.JTextArea desayuno_1;
    private javax.swing.JTextArea desayuno_2;
    private javax.swing.JTextArea desayuno_3;
    private javax.swing.JTextArea desayuno_4;
    private javax.swing.JTextArea desayuno_5;
    private javax.swing.JTextArea desayuno_6;
    private javax.swing.JTextArea desayuno_7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane61;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JScrollPane jScrollPane63;
    private javax.swing.JScrollPane jScrollPane64;
    private javax.swing.JScrollPane jScrollPane65;
    private javax.swing.JScrollPane jScrollPane66;
    private javax.swing.JScrollPane jScrollPane67;
    private javax.swing.JScrollPane jScrollPane68;
    private javax.swing.JScrollPane jScrollPane69;
    private javax.swing.JScrollPane jScrollPane70;
    private javax.swing.JScrollPane jScrollPane71;
    private javax.swing.JScrollPane jScrollPane72;
    private javax.swing.JScrollPane jScrollPane73;
    private javax.swing.JScrollPane jScrollPane74;
    private javax.swing.JScrollPane jScrollPane75;
    private javax.swing.JScrollPane jScrollPane76;
    private javax.swing.JScrollPane jScrollPane77;
    private javax.swing.JScrollPane jScrollPane78;
    private javax.swing.JScrollPane jScrollPane79;
    private javax.swing.JScrollPane jScrollPane80;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea t_cena_1;
    private javax.swing.JTextArea t_cena_2;
    private javax.swing.JTextArea t_cena_3;
    private javax.swing.JTextArea t_cena_4;
    private javax.swing.JTextArea t_cena_5;
    private javax.swing.JTextArea t_cena_6;
    private javax.swing.JTextArea t_cena_7;
    private javax.swing.JTextArea t_colacion1_1;
    private javax.swing.JTextArea t_colacion1_2;
    private javax.swing.JTextArea t_colacion1_3;
    private javax.swing.JTextArea t_colacion1_4;
    private javax.swing.JTextArea t_colacion1_5;
    private javax.swing.JTextArea t_colacion1_6;
    private javax.swing.JTextArea t_colacion1_7;
    private javax.swing.JTextArea t_colacion2_1;
    private javax.swing.JTextArea t_colacion2_2;
    private javax.swing.JTextArea t_colacion2_3;
    private javax.swing.JTextArea t_colacion2_4;
    private javax.swing.JTextArea t_colacion2_5;
    private javax.swing.JTextArea t_colacion2_6;
    private javax.swing.JTextArea t_colacion2_7;
    private javax.swing.JTextArea t_comida_1;
    private javax.swing.JTextArea t_comida_2;
    private javax.swing.JTextArea t_comida_3;
    private javax.swing.JTextArea t_comida_4;
    private javax.swing.JTextArea t_comida_5;
    private javax.swing.JTextArea t_comida_6;
    private javax.swing.JTextArea t_comida_7;
    private javax.swing.JTextArea t_desayuno_1;
    private javax.swing.JTextArea t_desayuno_2;
    private javax.swing.JTextArea t_desayuno_3;
    private javax.swing.JTextArea t_desayuno_4;
    private javax.swing.JTextArea t_desayuno_5;
    private javax.swing.JTextArea t_desayuno_6;
    private javax.swing.JTextArea t_desayuno_7;
    // End of variables declaration//GEN-END:variables
}
